AngularDummy/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NPoco;

namespace AngularDummy.Models
{
    [TableName("tblEmployees")]
    [PrimaryKey("Id")]
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Salary { get; set; }

    }
}

AngularDummy/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AngularDummy.Models;
using NPoco;

namespace AngularDummy.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get_AllEmployee()
        {
            using (IDatabase db = new Database("Primary"))
            {
                List<Employee> Emp = db.Fetch<Employee>("select * from tblEmployees");
                return Json(Emp, JsonRequestBehavior.AllowGet);
            }


           
        }

        //view to add Employee 
        public ActionResult Add()
        {
            return View();
        }

        public string Insert_Employee(Employee Emp)
        {
            if (Emp != null)
            {
                using (IDatabase db = new Database("Primary"))
                {
                 
                    db.Insert(Emp);
                    return "Employee Added Successfully";
                }
            }
            else
            {
                return "Employee Not Inserted! Try Again";
            }
        }


        public string Delete_Employee(Employee Emp)
        {
            if (Emp != null)
            {
                using (IDatabase db = new Database("Primary"))
                {

                    db.Delete(Emp);
                    return "Employee Deleted Successfully";
                }
            }
            else
            {
                return "Employee Not Deleted! Try Again";
            }
        }

        //view to add Employee 
        public ActionResult Update()
        {
            return View();
        }

        public string Update_Employee(Employee Emp)
        {
            if (Emp != null)
            {
                using (IDatabase db = new Database("Primary"))
                {

                    db.Update(Emp);
                    return "Employee Updated Successfully";
                }
            }
            else
            {
                return "Employee Not Updated! Try Again";
            }
        }
    }
}

AngularDummy/Views/Employee/Add.cshtml
@{
    ViewBag.Title = "Add Employee";
}
<style>
    .btn-space {
        margin-left: -5%;
        background-color: cornflowerblue;
        font-size: large;
    }
</style>

<h2>Addd new Employee</h2>
<div ng-app="myApp">
    <div ng-controller="myCtrl">

        <div class="form-group">
            <label class="col-md-4 control-label">Name:</label>
            <div class="col-md-8">
                <input type="text" class="form-control" id="inputName" placeholder="Name" ng-model="Name">
            </div>

        </div> <br />
        <div class="col-sm-6 col-lg-4">
            <div class="form-group">
                <label class="col-md-4 control-label">Gender:</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" id="inputGender" placeholder="Gender" ng-model="Gender">
                </div>
            </div>
        </div>  
        <br />
        <div class="col-sm-6 col-lg-4">
            <div class="form-group">
                <label class="col-md-4 control-label">Salary:</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" id="inputSalary" placeholder="Salary" ng-model="Salary">
                </div>
            </div>
        </div>  
        
        <br />
        <div class="row">
            <div class="col-sm-6 col-lg-4">
                <input type="button" id="btnSave" class="form-control btn-space" value="Submit" ng-click="InsertData()" />
            </div>
        </div> <br />
        <br />

        @Html.ActionLink("Go to Main", "Index", "Employee");

    </div>  
    
      
</div>

AngularDummy/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    .btn-space {
        margin-left: -5%;
        background-color: cornflowerblue;
        font-size: large;
    }
</style>

<h2>Index</h2>



<div ng-app="myApp">
    <div ng-controller="myCtrl" ng-init="GetAllData()" class="divList">
        <p class="divHead">List of Employee</p>
        <table cellpadding="12" class="table table-bordered table-hover">
            <tr>
                <td>
                    <b>ID</b>
                </td>
                <td>
                    <b>Name</b>
                </td>
                <td>
                    <b>Gender</b>
                </td>
                <td>
                    <b>Salary</b>
                </td>
                <td>
                    <b>Actions</b>
                </td>
            </tr>
            <tr ng-repeat="Emp in employees">
                <td>
                    {{Emp.Id}}
                </td>
                <td>
                    {{Emp.Name}}
                </td>
                <td>
                    {{Emp.Gender}}
                </td>
                <td>
                    {{Emp.Salary}}
                </td>
                <td>

                    <input type="button" class="btn btn-warning" value="Update" ng-click="UpdateEmp(Emp)" />
                    <input type="button" class="btn btn-danger" value="Delete" ng-click="DeleteEmp(Emp)" />
                </td>
            </tr>
        </table>
    
    <div class="form-horizontal" role="form">
        <div class="container">
            <div class="row">
                <h2>
                    <span id="spn">Add New Employee</span>
                </h2>
            </div>
            <div class="row">
                <div class="col-sm-6 col-lg-4">
                    <div class="form-group">
                        <label class="col-md-4 control-label">Name:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="inputEmail" placeholder="Name" ng-model="Name">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="form-group">
                        <label class="col-md-4 control-label">Gender:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="inputPassword" placeholder="Gender" ng-model="Gender">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="form-group">
                        <label class="col-md-4 control-label">Salary:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="inputLabel3" placeholder="Salary" ng-model="Salary">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-lg-4">
                    <input type="button" id="btnSave" class="form-control btn-space" value="Submit" ng-click="InsertData()" />
                </div>
            </div>
        </div>
    </div>
    @Html.Hidden("EmpID_")
</div>
</div>

AngularDummy/Views/Employee/Update.cshtml
@{
    ViewBag.Title = "Update Employee";
}
<style>
    .btn-space {
        margin-left: -5%;
        background-color: cornflowerblue;
        font-size: large;
    }
</style>

<h2>Update Employee</h2>
<div ng-app="myApp">
    <div ng-controller="myCtrl">

        <div class="form-group">
            <label class="col-md-4 control-label">Name:</label>
            <div class="col-md-8">
                <input type="text" class="form-control" id="inputName" placeholder="Name" ng-model="Name">
            </div>

        </div> <br />
        <div class="col-sm-6 col-lg-4">
            <div class="form-group">
                <label class="col-md-4 control-label">Gender:</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" id="inputGender" placeholder="Gender" ng-model="Gender">
                </div>
            </div>
        </div>
        <br />
        <div class="col-sm-6 col-lg-4">
            <div class="form-group">
                <label class="col-md-4 control-label">Salary:</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" id="inputSalary" placeholder="Salary" ng-model="Salary">
                </div>
            </div>
        </div>

        <br />
        <div class="row">
            <div class="col-sm-6 col-lg-4">
                <input type="button" id="btnSave" class="form-control btn-space" value="Submit" ng-click="InsertData()" />
            </div>
        </div> <br />
        <br />

        @Html.ActionLink("Go to Main", "Index", "Employee");

    </div>


</div>